package com.github.app.api.dao.mapper;

import com.github.app.api.dao.domain.Gateway;
import com.github.app.api.dao.domain.GatewayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GatewayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    long countByExample(GatewayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    int deleteByExample(GatewayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    int deleteByPrimaryKey(Integer gateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    int insert(Gateway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    int insertSelective(Gateway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    List<Gateway> selectByExampleWithBLOBs(GatewayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    List<Gateway> selectByExample(GatewayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    Gateway selectByPrimaryKey(Integer gateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") Gateway record, @Param("example") GatewayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Gateway record, @Param("example") GatewayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    int updateByExample(@Param("record") Gateway record, @Param("example") GatewayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    int updateByPrimaryKeySelective(Gateway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Gateway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    int updateByPrimaryKey(Gateway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Gateway selectOneByExample(GatewayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Gateway selectOneByExampleWithBLOBs(GatewayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Gateway> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Gateway> list, @Param("selective") Gateway.Column ... selective);
}