package com.github.app.api.dao.domain;

import java.util.Date;

public class Gateway {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway.gate_id
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    private Integer gateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway.host_name
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    private String hostName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway.port
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway.protocol_id
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    private Integer protocolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway.created_time
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway.last_modify_time
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway.config_properties
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    private String configProperties;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway.gate_id
     *
     * @return the value of gateway.gate_id
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public Integer getGateId() {
        return gateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway.gate_id
     *
     * @param gateId the value for gateway.gate_id
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public void setGateId(Integer gateId) {
        this.gateId = gateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway.host_name
     *
     * @return the value of gateway.host_name
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway.host_name
     *
     * @param hostName the value for gateway.host_name
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public void setHostName(String hostName) {
        this.hostName = hostName == null ? null : hostName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway.port
     *
     * @return the value of gateway.port
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway.port
     *
     * @param port the value for gateway.port
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway.protocol_id
     *
     * @return the value of gateway.protocol_id
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public Integer getProtocolId() {
        return protocolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway.protocol_id
     *
     * @param protocolId the value for gateway.protocol_id
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public void setProtocolId(Integer protocolId) {
        this.protocolId = protocolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway.created_time
     *
     * @return the value of gateway.created_time
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway.created_time
     *
     * @param createdTime the value for gateway.created_time
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway.last_modify_time
     *
     * @return the value of gateway.last_modify_time
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway.last_modify_time
     *
     * @param lastModifyTime the value for gateway.last_modify_time
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway.config_properties
     *
     * @return the value of gateway.config_properties
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public String getConfigProperties() {
        return configProperties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway.config_properties
     *
     * @param configProperties the value for gateway.config_properties
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public void setConfigProperties(String configProperties) {
        this.configProperties = configProperties == null ? null : configProperties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Gateway.Builder builder() {
        return new Gateway.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gateway
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table gateway
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Gateway obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table gateway
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Gateway();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column gateway.gate_id
         *
         * @param gateId the value for gateway.gate_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder gateId(Integer gateId) {
            obj.setGateId(gateId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column gateway.host_name
         *
         * @param hostName the value for gateway.host_name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder hostName(String hostName) {
            obj.setHostName(hostName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column gateway.port
         *
         * @param port the value for gateway.port
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder port(Integer port) {
            obj.setPort(port);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column gateway.protocol_id
         *
         * @param protocolId the value for gateway.protocol_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder protocolId(Integer protocolId) {
            obj.setProtocolId(protocolId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column gateway.created_time
         *
         * @param createdTime the value for gateway.created_time
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createdTime(Date createdTime) {
            obj.setCreatedTime(createdTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column gateway.last_modify_time
         *
         * @param lastModifyTime the value for gateway.last_modify_time
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder lastModifyTime(Date lastModifyTime) {
            obj.setLastModifyTime(lastModifyTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column gateway.config_properties
         *
         * @param configProperties the value for gateway.config_properties
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder configProperties(String configProperties) {
            obj.setConfigProperties(configProperties);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table gateway
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Gateway build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table gateway
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        gateId("gate_id"),
        hostName("host_name"),
        port("port"),
        protocolId("protocol_id"),
        createdTime("created_time"),
        lastModifyTime("last_modify_time"),
        configProperties("config_properties");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table gateway
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table gateway
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table gateway
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table gateway
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table gateway
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table gateway
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}