package com.github.app.api.dao.domain;

import java.util.Date;

public class Protocol {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column protocol.protocol_id
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    private Integer protocolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column protocol.name
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column protocol.created_time
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column protocol.last_modify_time
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column protocol.config_properties
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    private String configProperties;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column protocol.protocol_id
     *
     * @return the value of protocol.protocol_id
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public Integer getProtocolId() {
        return protocolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column protocol.protocol_id
     *
     * @param protocolId the value for protocol.protocol_id
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public void setProtocolId(Integer protocolId) {
        this.protocolId = protocolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column protocol.name
     *
     * @return the value of protocol.name
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column protocol.name
     *
     * @param name the value for protocol.name
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column protocol.created_time
     *
     * @return the value of protocol.created_time
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column protocol.created_time
     *
     * @param createdTime the value for protocol.created_time
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column protocol.last_modify_time
     *
     * @return the value of protocol.last_modify_time
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column protocol.last_modify_time
     *
     * @param lastModifyTime the value for protocol.last_modify_time
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column protocol.config_properties
     *
     * @return the value of protocol.config_properties
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public String getConfigProperties() {
        return configProperties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column protocol.config_properties
     *
     * @param configProperties the value for protocol.config_properties
     *
     * @mbg.generated Fri Jun 15 17:05:31 CST 2018
     */
    public void setConfigProperties(String configProperties) {
        this.configProperties = configProperties == null ? null : configProperties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table protocol
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Protocol.Builder builder() {
        return new Protocol.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table protocol
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table protocol
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Protocol obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table protocol
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Protocol();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column protocol.protocol_id
         *
         * @param protocolId the value for protocol.protocol_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder protocolId(Integer protocolId) {
            obj.setProtocolId(protocolId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column protocol.name
         *
         * @param name the value for protocol.name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder name(String name) {
            obj.setName(name);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column protocol.created_time
         *
         * @param createdTime the value for protocol.created_time
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createdTime(Date createdTime) {
            obj.setCreatedTime(createdTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column protocol.last_modify_time
         *
         * @param lastModifyTime the value for protocol.last_modify_time
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder lastModifyTime(Date lastModifyTime) {
            obj.setLastModifyTime(lastModifyTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column protocol.config_properties
         *
         * @param configProperties the value for protocol.config_properties
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder configProperties(String configProperties) {
            obj.setConfigProperties(configProperties);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table protocol
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Protocol build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table protocol
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        protocolId("protocol_id"),
        name("name"),
        createdTime("created_time"),
        lastModifyTime("last_modify_time"),
        configProperties("config_properties");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table protocol
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table protocol
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table protocol
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table protocol
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table protocol
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table protocol
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}